### ISSUE TITLE
Push 0.2.6 to hackage

### ISSUE THREAD

**Issue by menelaos** [robstewart57/hsparql#13]
Could you push 0.2.6 to hackage?

**Comment by robstewart57** [comment]
Done. https://hackage.haskell.org/package/hsparql

**Comment by menelaos** [comment]
Thanks! Currently, it doesn't build due to rdf4h still being at 1.3.0 on hackage. 
See https://github.com/robstewart57/rdf4h/issues/24.

**Comment by robstewart57** [comment]
@menelaos oops, thanks for notifying me. I'll upload 1.3.1 now.
