### ISSUE TITLE
the idea of a semantic web toolkit 

### ISSUE THREAD

**Issue by arademaker** [robstewart57/hsparql#47]
The readme says

> Develop a unified semantic web toolkit for Haskell Combining the RDF4H and hsparql packages seems like a sensible goal to achieve, to provide a semantic web toolkit similar to Jena for Java.

what about the following package?

https://hackage.haskell.org/package/swish

**Comment by robstewart57** [comment]
@arademaker Indeed, it would be good for the rdf4h and swish packages to have a common set of types for triples, nodes, IRIs, RDF graphs, etc. Currently, the hsparql package uses the types and functions provided by rdf4h.
